frase = str(input('Digite uma frase qualquer: ')).strip()
frase = frase.upper()
print('A letra A aparece {} vezes'.format(frase.count('A')))
print('A primeira letra A aparece na posição {} '.format(frase.find('A')+1))
print('A ùltima letra A aparece na posição {} '.format(frase.rfind('A')))
